import { Client } from "../client/Client";
import { Base } from "./Base";
import { Guild } from "./Guild";
declare class Member extends Base {
    #private;
    readonly guild: Guild;
    joined: any;
    user: any;
    muted: any;
    deafened: any;
    flags: any;
    permissions: any;
    role_ids: any;
    roles: any;
    presence: any;
    nick: any;
    avatar: any;
    premiumSince: any;
    pending: any;
    communicationDisabledUntil: any;
    timeoutUntil: any;
    communicationDisabled: any;
    timeouted: any;
    constructor(data: Record<any, any>, guild: Guild, client: Client);
    get author(): any;
    _patch(data: any): void;
    leave(): void;
    get kickable(): boolean;
    get banneable(): boolean;
    edit(obj: any): Promise<boolean>;
    changeNickname(nickname: string, reason: string): Promise<import("../interfaces/rest/requestHandler").ResponseFromApi | import("../interfaces/rest/requestHandler").ErrorResponseFromApi | null>;
    kick(reason: string): Promise<import("../interfaces/rest/requestHandler").ResponseFromApi | import("../interfaces/rest/requestHandler").ErrorResponseFromApi | null>;
    ban(obj: any): Promise<import("../interfaces/rest/requestHandler").ResponseFromApi | import("../interfaces/rest/requestHandler").ErrorResponseFromApi | null>;
    toString(): string;
}
export { Member };
