"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventNames = void 0;
var EventNames;
(function (EventNames) {
    EventNames["Debug"] = "debug";
    EventNames["MessageCreate"] = "messageCreate";
    EventNames["InteractionCreate"] = "interactionCreate";
    EventNames["ChannelCreate"] = "channelCreate";
    EventNames["ChannelDelete"] = "channelDelete";
    EventNames["ChannelUpdate"] = "channelUpdate";
    EventNames["GuildBanAdd"] = "guildBanAdd";
    EventNames["GuildBanRemove"] = "guildBanRemove";
    EventNames["Ready"] = "ready";
    EventNames["ThreadCreate"] = "threadCreate";
    EventNames["ThreadUpdate"] = "threadUpdate";
    EventNames["ThreadDelete"] = "threadDelete";
    EventNames["ThreadListSync"] = "threadListSync";
    EventNames["ThreadMemberUpdate"] = "threadMemberUpdate";
    EventNames["GuildCreate"] = "guildCreate";
    EventNames["GuildUnavailable"] = "guildUnavailable";
    EventNames["GuildDelete"] = "guildDelete";
    EventNames["GuildEmojiUpdate"] = "guildEmojiUpdate";
    EventNames["GuildMemberAdd"] = "guildMemberAdd";
    EventNames["GuildMemberChunk"] = "guildMemberChunk";
    EventNames["GuildMemberLeave"] = "guildMemberLeave";
    EventNames["GuildMemberUpdate"] = "guildMemberUpdate";
    EventNames["GuildRoleCreate"] = "guildRoleCreate";
    EventNames["GuildRoleDelete"] = "guildRoleDelete";
    EventNames["GuildRoleUpdate"] = "guildRoleUpdate";
    EventNames["GuildStickersUpdate"] = "guildStickersUpdate";
    EventNames["GuildUpdate"] = "guildUpdate";
    EventNames["MessageDelete"] = "messageDelete";
    EventNames["MessageUpdate"] = "messageUpdate";
    EventNames["PresenceUpdate"] = "presenceUpdate";
    EventNames["VoiceServerUpdate"] = "voiceServerUpdate";
    EventNames["VoiceStateUpdate"] = "voiceStateUpdate";
    EventNames["RawEvent"] = "rawEvent";
})(EventNames || (exports.EventNames = EventNames = {}));
// bueno, la IA se llama tabnine
