"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PermissionsNames = void 0;
var PermissionsNames;
(function (PermissionsNames) {
    // Roles
    PermissionsNames["CreateInstantInvite"] = "CreateInstantInvite";
    PermissionsNames["KickMembers"] = "KickMembers";
    PermissionsNames["BanMembers"] = "BanMembers";
    PermissionsNames["Administrator"] = "Administrator";
    PermissionsNames["ManageChannels"] = "ManageChannels";
    PermissionsNames["ManageGuilds"] = "ManageGuilds";
    PermissionsNames["AddReactions"] = "AddReactions";
    PermissionsNames["ViewAuditLog"] = "ViewAuditLog";
    PermissionsNames["PrioritySpeaker"] = "PrioritySpeaker";
    PermissionsNames["Stream"] = "Stream";
    PermissionsNames["ViewChannel"] = "ViewChannel";
    PermissionsNames["SendMessages"] = "SendMessages";
    PermissionsNames["SendTTSMessages"] = "SendTTSMessages";
    PermissionsNames["ManageMessages"] = "ManageMessages";
    PermissionsNames["EmbedLinks"] = "EmbedLinks";
    PermissionsNames["AttachFiles"] = "AttachFiles";
    PermissionsNames["ReadMessageHistory"] = "ReadMessageHistory";
    PermissionsNames["MentionEveryone"] = "MentionEveryone";
    PermissionsNames["UseExternalEmojis"] = "UseExternalEmojis";
    PermissionsNames["ViewGuildInsights"] = "ViewGuildInsights";
    PermissionsNames["Connect"] = "Connect";
    PermissionsNames["Speak"] = "Speak";
    PermissionsNames["MuteMembers"] = "MuteMembers";
    PermissionsNames["DeafenMembers"] = "DeafenMembers";
    PermissionsNames["MoveMembers"] = "MoveMembers";
    PermissionsNames["UseVAD"] = "UseVAD";
    PermissionsNames["ChangeNickname"] = "ChangeNickname";
    PermissionsNames["ManageNicknames"] = "ManageNicknames";
    PermissionsNames["ManageRoles"] = "ManageRoles";
    PermissionsNames["ManageWebhooks"] = "ManageWebhooks";
    PermissionsNames["ManageEmojis"] = "ManageEmojis";
    // Channels
    PermissionsNames["ChannelCreateInstantInvite"] = "CreateInstantInvite";
    PermissionsNames["ChannelManageChannels"] = "ManageChannels";
    PermissionsNames["ChannelManageRoles"] = "ManageRoles";
    PermissionsNames["ChannelManageWebhooks"] = "ManageWebhooks";
    PermissionsNames["ChannelViewChannel"] = "ViewChannel";
    PermissionsNames["ChannelSendMessages"] = "SendMessages";
    PermissionsNames["ChannelSendTTSMessages"] = "SendTTSMessages";
    PermissionsNames["ChannelManageMessages"] = "ManageMessages";
    PermissionsNames["ChannelEmbedLinks"] = "EmbedLinks";
    PermissionsNames["ChannelAttachFiles"] = "AttachFiles";
    PermissionsNames["ChannelReadMessageHistory"] = "ReadMessageHistory";
    PermissionsNames["ChannelMentionEveryone"] = "MentionEveryone";
    PermissionsNames["ChannelUseExternalEmojis"] = "UseExternalEmojis";
    PermissionsNames["ChannelConnect"] = "Connect";
    PermissionsNames["ChannelSpeak"] = "Speak";
    PermissionsNames["ChannelMuteMembers"] = "MuteMembers";
    PermissionsNames["ChannelDeafenMembers"] = "DeafenMembers";
    PermissionsNames["ChannelMoveMembers"] = "MoveMembers";
    PermissionsNames["ChannelUseVAD"] = "UseVAD";
    PermissionsNames["ChannelPrioritySpeaker"] = "PrioritySpeaker";
    PermissionsNames["ChannelStream"] = "Stream";
})(PermissionsNames || (exports.PermissionsNames = PermissionsNames = {}));
